[package]
name = "wasm"
version = "0.1.0"
authors = ["Pascal Galle <p.galle@studio-b12.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.68"
